name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 9.5.0+1
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_android
      ios:
        default_package: stripe_ios
      web:
        default_package: stripe_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  stripe_android:
    git:
      url: https://github.com/artemsorochan/flutter_stripe.git
      path: packages/stripe_android
      ref: main
  stripe_ios:
    git:
      url: https://github.com/artemsorochan/flutter_stripe.git
      path: packages/stripe_ios
      ref: main
  stripe_platform_interface:
    git:
      url: https://github.com/artemsorochan/flutter_stripe.git
      path: packages/stripe_platform_interface
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
